# Standards: 0.1
---
- name: Create required dirs
  with_items:
    - /etc/traefik
  file:
    path: "{{ item }}"
    state: directory
  tags:
    - traefik

- name: Write general config
  notify:
    - Reload traefik
  template:
    src: config.j2
    dest: /etc/traefik/traefik.yml
  tags:
    - traefik

- name: Write static config
  notify:
    - Reload traefik
  template:
    src: static.j2
    dest: /etc/traefik/static.yml
  tags:
    - traefik

- name: Write env default
  notify:
    - Restart traefik
  template:
    src: default.j2
    dest: /etc/default/traefik
  tags:
    - traefik

- name: Write service file
  notify:
    - Restart traefik
  template:
    src: service.j2
    dest: /etc/systemd/system/traefik.service
  tags:
    - traefik

- name: Start traefik service
  systemd:
    name: traefik
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - traefik

...
