# Standards: 1.2
---
- name: Create required dirs
  with_items:
    - /etc/traefik
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  tags:
    - traefik

- name: Write general config
  notify:
    - Reload traefik
  template:
    src: config.j2
    dest: /etc/traefik/traefik.yml
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - traefik

- name: Write static config
  notify:
    - Reload traefik
  template:
    src: static.j2
    dest: /etc/traefik/static.yml
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - traefik

- name: Write env default
  notify:
    - Restart traefik
  template:
    src: default.j2
    dest: /etc/default/traefik
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - traefik

- name: Write service file
  notify:
    - Restart traefik
  template:
    src: service.j2
    dest: /etc/systemd/system/traefik.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - traefik

- name: Pull docker image
  when:
    - traefik_pull_image
  docker_image:
    name: "{{ traefik_image }}"
    source: pull
  tags:
    - traefik

- name: Create docker network
  when:
    - traefik_network | default(False)
  docker_network:
    name: '{{ traefik_network }}'
  tags:
    - traefik

- name: Start traefik service
  systemd:
    name: traefik
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - traefik

...
