# Standards: 0.1
---
- name: Define docker network
  docker_network:
    name: '{{ traefik_docker_network_name }}'
    enable_ipv6: '{{ traefik_network_ipv6 }}'
    ipam_config: '{{ traefik_network_ipam_config }}'
  tags:
    - traefik

- name: Create required dirs
  with_items:
    - /etc/traefik
  file:
    path: '{{ item }}'
    state: directory
  tags:
    - traefik

- name: Write general config
  notify:
    - Reload traefik
  template:
    src: config.j2
    dest: /etc/traefik/traefik.yml
  tags:
    - traefik

- name: Write static config
  notify:
    - Reload traefik
  template:
    src: static.j2
    dest: /etc/traefik/static.yml
  tags:
    - traefik

- name: Write env default
  notify:
    - Restart traefik
  template:
    src: default.j2
    dest: /etc/default/traefik
  tags:
    - traefik

- name: Write service file
  notify:
    - Restart traefik
  template:
    src: service.j2
    dest: /etc/systemd/system/traefik.service
  tags:
    - traefik

- name: Start traefik service
  systemd:
    name: traefik
    state: started
    daemon_reload: yes
    masked: no
    enabled: yes
  tags:
    - traefik

...
