---
- name: Restart traefik
  ansible.builtin.systemd:
    name: traefik
    state: restarted
    daemon_reload: True

- name: Reload traefik
  ansible.builtin.systemd:
    name: traefik
    state: '{{ "restarted" if traefik_force_restart else "reloaded" }}'
    daemon_reload: True

...
